### ISSUE TITLE
Issue with ssl.truststore.location & ssl.keystore.location

### ISSUE THREAD

**Issue by e3aa3b** [tmgstevens/spark-streaming-kafka09#1]
Hi,

I was trying to consume the API using the documentation and continuously hitting a road block with truststore & keystore location when I execute my script via spark-submit. It hits 'filenotfound' exception:

17/09/04 03:08:16 WARN TaskSetManager: Lost task 0.0 in stage 4.0 (TID 4, hdstg-c01-r03-02, executor 1): org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
        at org.apache.kafka.clients.consumer.KafkaConsumer.initializeConsumer(KafkaConsumer.java:733)
        at org.apache.kafka.clients.consumer.KafkaConsumer.assign(KafkaConsumer.java:1063)
        at org.apache.spark.streaming.kafka09.CachedKafkaConsumer.<init>(CachedKafkaConsumer.scala:51)
        at org.apache.spark.streaming.kafka09.CachedKafkaConsumer$.get(CachedKafkaConsumer.scala:168)
        at org.apache.spark.streaming.kafka09.KafkaRDD$KafkaRDDIterator.<init>(KafkaRDD.scala:214)
        at org.apache.spark.streaming.kafka09.KafkaRDD.compute(KafkaRDD.scala:189)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: java.io.FileNotFoundException: /directory/kafka.client.keystore.jks (No such file or directory)
        at org.apache.kafka.common.network.SslChannelBuilder.configure(SslChannelBuilder.java:44)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79)
        at org.apache.kafka.clients.consumer.KafkaConsumer.initializeConsumer(KafkaConsumer.java:662)
        ... 13 more
 
The file is present in both unix local FS & Hadoop FS. I am not sure if something is broken here, but the library just doesnt pick the location for trust & key store. A similar code in Java (running as standalone program) picks it up easily. So doesn't seem like a read issue on the file either.

Have you noticed an issue for the same?

Thanks

**Comment by parvep29** [comment]
Are you able to resolve this ? I am facing same isssue using kafka 0-10

**Comment by tmgstevens** [comment]
I've never seen this before. Normally the truststore would go into $JAVA_HOME/jre/lib/security/jssecacerts, so it would get picked up automatically. You could use --conf "spark.executor.extraJavaOptions=-Djavax.net.ssl.trustStore=/path/ts-name". I looked at the Kafka code for this the other day, and it will pick up the system one, if configured. Try that. Otherwise, I'd be on to support. I take it, the truststore, and specifically the whole path has read permissions?
